use jew_shop
CREATE TABLE Client
(
id BIGINT PRIMARY KEY IDENTITY,
surname NVARCHAR(50) NOT NULL,
first_name NVARCHAR(50) NOT NULL,
second_name NVARCHAR(50) NOT NULL,
adress NVARCHAR(50),
phone_number NVARCHAR(50) NOT NUll
)
CREATE TABLE Shop
(
id BIGINT PRIMARY KEY IDENTITY,
adress NVARCHAR(50) NOT NULL,
phone_number NVARCHAR(50) NOT NULL,
email NVARCHAR(50) NOT NULL,
postcode NVARCHAR(50) NOT NULL,
staff_id BIGINT NOT NULL,
)
CREATE TABLE Employee
(
id BIGINT PRIMARY KEY IDENTITY,
first_name NVARCHAR(50) NOT NULL,
last_name NVARCHAR(50) NOT NULL,
second_name NVARCHAR(50) NOT NULL,
position NVARCHAR(50) NOT NULL,
salary MONEY NOT NULL,
adress NVARCHAR(50) NOT NULL,
phone_number NVARCHAR(50) NOT NULL,
shop_info BIGINT NOT NULL,
CONSTRAINT FK_Shop_Employee FOREIGN KEY (shop_info) REFERENCES Shop(id) ON UPDATE CASCADE ON
DELETE NO ACTION
)
CREATE TABLE Product
(
id BIGINT PRIMARY KEY IDENTITY,
name NVARCHAR(50) NOT NULL,
)
CREATE TABLE Order_info
(
id BIGINT PRIMARY KEY IDENTITY,
client_id BIGINT NOT NULL,
product_id BIGINT NOT NULL,
order_date DATETIME NOT NULL,
status BIT NOT NULL,
cataloge_id BIGINT NOT NULL,
seller_id BIGINT NOT NULL,
CONSTRAINT FK_Employee_Order FOREIGN KEY(seller_id) REFERENCES Employee(id) ON UPDATE
CASCADE ON DELETE NO ACTION,
CONSTRAINT FK_Client_Order FOREIGN KEY (client_id) REFERENCES Client(id) ON UPDATE CASCADE
ON DELETE NO ACTION,
CONSTRAINT FK_Catalog_Order FOREIGN KEY (cataloge_id) REFERENCES Catalog(id) ON UPDATE
CASCADE ON DELETE NO ACTION
)
CREATE TABLE Catalog
(
id BIGINT PRIMARY KEY IDENTITY,
product_id BIGINT NOT NULL,
shop_id BIGINT NOT NULL,
price MONEY NOT NULL,
quantity BIGINT NOT NULL,
CONSTRAINT FK_Product_Catalog FOREIGN KEY (product_id) REFERENCES Product(id) ON UPDATE
CASCADE ON DELETE NO ACTION,
CONSTRAINT FK_Shop_Catalog FOREIGN KEY (shop_id) REFERENCES Shop(id) ON UPDATE CASCADE ON
DELETE NO ACTION
)